export const PROTOCOL_VERSION = 1;
export const DEFAULT_WS_PORT = 7331;
export const DEFAULT_HTTP_PORT = 7332;
export const MDNS_SERVICE_NAME = "_cc-room._tcp";
export const SECRET_BYTES = 32;
export const NONCE_BYTES = 32;
export const AUTH_TIMEOUT_MS = 5_000;
export const PING_INTERVAL_MS = 15_000;
export const PING_MISS_THRESHOLD = 3;
export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024; // 10MB
export const FILE_CHUNK_SIZE_BYTES = 64 * 1024; // 64KB
export const CHUNK_TIMEOUT_MS = 30_000;
export const FILE_TRANSFER_TIMEOUT_MS = 5 * 60 * 1000; // 5min
export const RECONNECT_BASE_DELAY_MS = 1_000;
export const RECONNECT_MAX_DELAY_MS = 30_000;
export const RECONNECT_MAX_ATTEMPTS = 10;
export const RECONNECT_JITTER = 0.2;
export const HEALTH_CHECK_INTERVAL_MS = 30_000;
export const STORAGE_CLEANUP_INTERVAL_MS = 60 * 60 * 1000; // 1h
export const DEFAULT_MAX_STORAGE_BYTES = 500 * 1024 * 1024; // 500MB
export const DEFAULT_ARTIFACT_TTL_DAYS = 30;
export const DEFAULT_CONTEXT_TTL_DAYS = 7;
export const DEFAULT_MESSAGE_TTL_DAYS = 14;
export const SUMMARIZER_MAX_RETRIES = 3;
export const SUMMARIZER_FALLBACK_DURATION_MS = 5 * 60 * 1000; // 5min
export const ROOM_NAME_MAX_LENGTH = 32;
export const PIN_LENGTH = 6;
export const AUTH_MAX_ATTEMPTS_PER_MIN = 3;
